# Device variables
device : cuda
n_gpu : 1
n_gpu_nodes : 1
num_workers : 1
client_id : 1
num_clients : 2
set_server : False

# Model variables
federated : False
local_model : UNet
load_checkpoint : None
task : Segmentation
in_channels : 1
n_classes : 4
UNet_depth : 3
UNet_bilinear : True
UNet_custom_shape : None # [(1,64),(64,128),(128,256),(256,512),(512,1024)]

# Training variables
batch_size : 2
train_size : 0.8
val_size : 0.1
test_size : 0.1
epochs : 100
num_rounds : 10
verbatim : False

epochs_per_round : [5,10,15,20]
# Meaning 5 epochs in round 0,10 in round 1, ...

# Optimizer variables
optimizer : Adam # 'Adam' or 'SGD'
dropout : 0.1
lr : 0.001
lr_min : 1e-7
lr_factor : 0.5
lr_patience : 10
lr_scheduler : ReduceLROnPlateau
clip : 1.0
early_stopping_patience : 10

# Data set variables
dataset : LightningWrapperData
dataset_root : /home/corn/workdir/Federado-main/flower_version/data/MMs/MMs_3_reshaped.pt
target_label : mask
n_channels : 1
#data/CIFAR/cifar_1.pt

# Logging variables
log_path : Segmentation_3
every_n_epochs : 1
wandb_track : True
wandb_project : AIHF_Demo
wandb_run_name : Seg_3
wandb_entity': 'jorgefabila1997'
save_top_k : 10
