# Device variables
device : cuda
n_gpu : 1
n_gpu_nodes : 1
num_workers : 1
use_certificates : False
client_id : 1
num_clients : 5
set_server : False
server_address : 0.0.0.0:8080
#161.116.4.119:4433

# Model variables
federated : True
local_model : UNet
load_checkpoint : segmentador_dice.ckpt
task : Segmentation
in_channels : 1
n_classes : 4
UNet_depth : 3
UNet_bilinear : True
UNet_custom_shape : None

# Training variables
batch_size : 1
train_size : 0.2
val_size : 0.05
test_size : 0.05
epochs : 3
num_rounds : 10
verbatim : False

epochs_per_round : [5,10,15,20]
# Meaning 5 epochs in round 0,10 in round 1, ...

# Optimizer variables
optimizer : Adam # 'Adam' or 'SGD'
dropout : 0.1
lr : 0.001
lr_min : 1e-7
lr_factor : 0.5
lr_patience : 10
lr_scheduler : ReduceLROnPlateau
clip : 1.0
early_stopping_patience : 10

# Data set variables
dataset : LightningWrapperData
dataset_root : /home/jorge/work_dir/AIHF_Demo/data/MMs_1_reshaped.pt
target_label : mask
n_channels : 1
#data/CIFAR/cifar_1.pt

# Logging variables
log_path : Segmentation_1
every_n_epochs : 1
wandb_track : True
wandb_project : AIHF_Demo
wandb_run_name : Seg_1
wandb_entity: 'jorgefabila1997'
save_top_k : 10
